#In this notebook we will cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting Information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Execises to "stick the landing"


## Introduction to Tensors

In [16]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.8.2


In [17]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [5]:
# Create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimensions of our vector

vector.ndim

1

In [7]:
# Create a matrix (more than 1 dimensions)

matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
# Check the number dimensions of an matrix

matrix.ndim

2

In [9]:
# Create another matrix

another_matrix = tf.constant([[10.,7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16) #specify the data type with dtype parametar

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim #total number of dimenstions is equal to the number of "shape" values

2

In [11]:
# Let's create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8 ,9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector )

### Creating tensors with "tf.Variable"

In [13]:
# Create the same tensor with tf.Variable() as above

changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try changing one of the elements in our changable tensor

changable_tensor[0] = 7
changable_tensor

TypeError: ignored

In [ ]:
# How about we try .assign()

changable_tensor[0].assign(7)
changable_tensor

In [ ]:
# Let's try changing our unchangable tensor

unchangable_tensor[0].assign(7)
unchangable_tensor

**NOTES:** Rarely in practice will you need to decide whether to use 'tf.constanst' or 'tf.Variable' to create tensors, as TensorFlow does this for you. However, if in doubt, use 'tf.constant' and change it later if needed.

### Creating random tensors

Random tensors are tensors of some abitrary size whitch contain random numbers

In [ ]:
# Create two but random tensors

random_1 = tf.random.Generator.from_seed(42) # setting the seed "flavours" the random generator with the number 42
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(6)
random_2 = random_2.normal(shape=(3,2))

# Are they equal
random_1, random_2, random_1 == random_2


### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the ingherent order doesn't effenct learning)

not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle our non-shuffled tensor
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled, seed=42) #if we put operation and global level seeds, the suffled tensors wičč be in the same order (both seeds are used in conjuction) 

### Other ways to make tensors

In [ ]:
# Create a tensor of all ones

tf.ones([10, 7])

In [ ]:
# Create a tensor of all zeroes

tf.zeros(shape=(3,4))

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TesnsorFlow tensors in that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy between 1 and 25
numpy_A

# X = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector) #non-capital for vector

In [ ]:
A = tf.constant(numpy_A)
A # now the same NumPy array is a tensor

In [ ]:
B = tf.constant(numpy_A, shape=(2, 3, 4)) #shape needs to multiply to the total number of elements in the original array (2*3*4=24)
B # 3D tensor

### Getting information from tensors

When dealing with tensors you probably want to be aware of the folowing atributes:
* Shape
* Rank
* Axis or dimension
* Size

In [18]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [19]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [20]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [21]:
2*3*4*5 # shape property (numpy=120)

120

In [23]:
from tensorflow.python.ops.gen_array_ops import rank
#Get various atributes of ur tensor

print("Datatyoe of evety element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axies: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor (shorter): ", tf.size(rank_4_tensor).numpy())

Datatyoe of evety element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axies:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor (shorter):  120
