#In this notebook we will cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting Information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Execises to "stick the landing"


## Introduction to Tensors

In [1]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2023-01-23 13:42:11.990237: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-23 13:42:12.228236: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-23 13:42:12.228257: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-23 13:42:13.214816: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

2.11.0


In [2]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar


2023-01-23 13:42:15.022651: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-01-23 13:42:15.022907: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-23 13:42:15.022966: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2023-01-23 13:42:15.023003: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2023-01-23 13:42:15.023037: W tensorflow/c

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [4]:
# Create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimensions of our vector

vector.ndim

1

In [6]:
# Create a matrix (more than 1 dimensions)

matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check the number dimensions of an matrix

matrix.ndim

2

In [8]:
# Create another matrix

another_matrix = tf.constant([[10.,7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16) #specify the data type with dtype parametar

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim #total number of dimenstions is equal to the number of "shape" values

2

In [10]:
# Let's create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8 ,9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector )

### Creating tensors with "tf.Variable"

In [12]:
# Create the same tensor with tf.Variable() as above

changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try changing one of the elements in our changable tensor

changable_tensor[0] = 7
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()

changable_tensor[0].assign(7)
changable_tensor

In [14]:
# Let's try changing our unchangable tensor

unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

**NOTES:** Rarely in practice will you need to decide whether to use 'tf.constanst' or 'tf.Variable' to create tensors, as TensorFlow does this for you. However, if in doubt, use 'tf.constant' and change it later if needed.

### Creating random tensors

Random tensors are tensors of some abitrary size whitch contain random numbers

In [15]:
# Create two but random tensors

random_1 = tf.random.Generator.from_seed(42) # setting the seed "flavours" the random generator with the number 42
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(6)
random_2 = random_2.normal(shape=(3,2))

# Are they equal
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.97061104, -1.0242516 ],
        [-0.6544423 , -0.29738766],
        [-1.3240396 ,  0.28785667]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle the order of elements in a tensor

In [16]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the ingherent order doesn't effenct learning)

not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# Shuffle our non-shuffled tensor
tf.random.set_seed(42) #global level seed
tf.random.shuffle(not_shuffled, seed=42) #if we put operation and global level seeds, the suffled tensors wičč be in the same order (both seeds are used in conjuction) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [17]:
# Create a tensor of all ones

tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
# Create a tensor of all zeroes

tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TesnsorFlow tensors in that tensors can be run on a GPU (much faster for numerical computing)

In [19]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy between 1 and 25
numpy_A

# X = tf.constant(some_matrix) #capital for matrix or tensor
# y = tf.constant(vector) #non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(numpy_A)
A # now the same NumPy array is a tensor

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [21]:
B = tf.constant(numpy_A, shape=(2, 3, 4)) #shape needs to multiply to the total number of elements in the original array (2*3*4=24)
B # 3D tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors

When dealing with tensors you probably want to be aware of the folowing atributes:
* Shape
* Rank
* Axis or dimension
* Size

In [22]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
2*3*4*5 # shape property (numpy=120)

120

In [26]:
from tensorflow.python.ops.gen_array_ops import rank
#Get various atributes of ur tensor

print("Datatyoe of evety element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axies: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in our tensor (shorter): ", tf.size(rank_4_tensor).numpy())

Datatyoe of evety element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axies:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor (shorter):  120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [27]:
some_list =  [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [28]:
# Get the first 2 elements of each dimension 

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [30]:
# Get the first element form each dimension from each index exept for the final one

rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
# Get the first element form each dimension from each index exept for the second to last one

rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [32]:
# Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [33]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [34]:
# Last element of a list

some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [35]:
# Get the last item of each row of our rank 2 tensor 

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [36]:
# Add in extra dimenson to our rank 2 tensor 

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [37]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1)  # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [38]:
tf.expand_dims(rank_2_tensor, axis=0) # now our extra dimension is in the front

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [39]:
tf.expand_dims(rank_2_tensor, axis=1) # now our extra dimension is in the middle 

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic Operations**
+, -, *, /

In [40]:
# You can add values to a tensor using the additition operator

tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [41]:
# Original tensor is unchanged

tensor

# except if we do tensor = tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [42]:
# Multiplication

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [43]:
# Substraction

tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [44]:
# We can use the tensorflow built-in function too

tf.math.multiply(tensor, 10)
#or
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix multiplication

In machine learning, matrix multiplication is one of the most common tensor operations.

There are 2 rules tensors (or matrices) need to fulfill if we' re going to matrix multiply them:
   1. The inner dimensions must match
   2. The resulting matrix has the shape of the outer dimensions

In [45]:
# Matrix multiplication in tensorflow

print(tensor)

tf. matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [46]:
# Matric multiplication with python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [47]:
tensor.shape

TensorShape([2, 2])

In [48]:
# Matrix multiplication on tensors of same shape

# create a (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# create a (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X @ Y

# This does not work because does not work because of the before stated rules for matrix multiplication.


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [49]:
# Let's change the shape of Y

tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [50]:
# Try to matrix multiply X by reshaped Y

X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [52]:
# Try change the shape of X instead of Y

tf.matmul(tf.reshape(X, shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [53]:
# Can do the same with transpose

X, tf.transpose(X), tf.reshape(X, shape=(2,3))

#Transpose flips the axes 

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [54]:
# Try matrix multiplication with transpose rather than reshape

tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix multiplication is also refered to as the dot product.

You can preform matrix multiplication using:
* 'tf.matmul()'
* 'tf.tensordot()'
* '@'

In [55]:
# Preform the dot product on X and Y (requires X or Y to be transposed)

X, Y

tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [56]:
# Preform matrix multiplication between X and Y(transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [57]:
# Preform matrix multiplication between X and Y(reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [58]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y: ")
print(Y, "\n")
print("Reshaped Y: ")
print(tf.reshape(Y, shape=(2,3)), "\n")
print("Transposed Y: ")
print(tf.transpose(Y))

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y: 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


### Changing the datatype of a tensor

* default dtype is float32

In [59]:
# Create a new tensor with default datatype (float32)

B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [61]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [62]:
# Change from float32 to float16 (reducet precision)

D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [67]:
# Change from int32 to float32

E = tf.cast(C, dtype =tf.float32)
print("Float 32: ")
print(E, E.dtype, "\n")

#Change from float32 to float16

E_float16 = tf.cast(E, dtype=tf.float16)
print("Float16: ")
print(E_float16, E_float16.dtype, "\n")

Float 32: 
tf.Tensor([ 7. 10.], shape=(2,), dtype=float32) <dtype: 'float32'> 

Float16: 
tf.Tensor([ 7. 10.], shape=(2,), dtype=float16) <dtype: 'float16'> 



### Aggregating tensors

Aggregating tensors = condensing them form multiple values down to a smaller amount of values

In [69]:
# Get the absolute values 
# (returns the absolute value of corresponding element in tensor)

D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor (avrage)
* Get the sum of a tensor

In [70]:
# Create a random tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0, 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([91, 18, 10, 36,  9, 84, 35, 45, 33, 88, 58, 27, 11,  3, 71, 78, 29,
       45, 87, 48, 15, 20, 15, 75, 73, 67, 70,  9, 70,  6, 22, 86, 35, 90,
       46, 58, 45, 13, 45, 63, 45, 14, 70,  2, 47, 26, 32, 55, 21, 65])>

In [82]:
E, tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([91, 18, 10, 36,  9, 84, 35, 45, 33, 88, 58, 27, 11,  3, 71, 78, 29,
        45, 87, 48, 15, 20, 15, 75, 73, 67, 70,  9, 70,  6, 22, 86, 35, 90,
        46, 58, 45, 13, 45, 63, 45, 14, 70,  2, 47, 26, 32, 55, 21, 65])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1)

In [72]:
# Find the minimum 

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [73]:
# Find the maximum

tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=91>

In [74]:
# Find the mean

tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [75]:
# Find the sum

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2206>

In [84]:
# Find the variance

E_float32 = tf.cast(E, dtype=tf.float32)
tf.math.reduce_variance(E_float32)

<tf.Tensor: shape=(), dtype=float32, numpy=715.7456>

In [81]:
# Find the standard deviation

tf.math.reduce_std(E_float32)

<tf.Tensor: shape=(), dtype=float32, numpy=26.753422>

### Find the positional maximum and minimum



In [88]:
# Create a new tensor for finding positional minimim and maximum

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [95]:
# Find the positional maximum and index on our largest value position

tf.argmax(F), F[tf.argmax(F)], tf.reduce_max(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [96]:
# Find the positional minimum and index on our lowest value position

tf.argmin(F), F[tf.argmin(F)], tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a tensor (removing all single dimension axes)

In [99]:
# Create a tensor to get started

G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7402308 , 0.33938193, 0.5692506 , 0.44811392, 0.29285502,
           0.4260056 , 0.62890387, 0.691061  , 0.30925727, 0.89236605,
           0.66396606, 0.30541587, 0.8724164 , 0.1025728 , 0.56819403,
           0.25427842, 0.7253866 , 0.4770788 , 0.46289814, 0.88944995,
           0.6792555 , 0.09752727, 0.01609659, 0.4876021 , 0.5832968 ,
           0.41212583, 0.731905  , 0.93418944, 0.5298122 , 0.9664817 ,
           0.88391197, 0.10578597, 0.44439578, 0.7851516 , 0.47332513,
           0.89893615, 0.04290593, 0.8717004 , 0.6068529 , 0.12963045,
           0.4527359 , 0.24573493, 0.34777248, 0.582147  , 0.82298195,
           0.82862926, 0.877372  , 0.5319803 , 0.03594303, 0.03986669]]]]],
      dtype=float32)>

In [105]:
G_squeeze = tf.squeeze(G)
print(G.shape, "\n", G_squeeze, "\n", G_squeeze.shape)

(1, 1, 1, 1, 50) 
 tf.Tensor(
[0.7402308  0.33938193 0.5692506  0.44811392 0.29285502 0.4260056
 0.62890387 0.691061   0.30925727 0.89236605 0.66396606 0.30541587
 0.8724164  0.1025728  0.56819403 0.25427842 0.7253866  0.4770788
 0.46289814 0.88944995 0.6792555  0.09752727 0.01609659 0.4876021
 0.5832968  0.41212583 0.731905   0.93418944 0.5298122  0.9664817
 0.88391197 0.10578597 0.44439578 0.7851516  0.47332513 0.89893615
 0.04290593 0.8717004  0.6068529  0.12963045 0.4527359  0.24573493
 0.34777248 0.582147   0.82298195 0.82862926 0.877372   0.5319803
 0.03594303 0.03986669], shape=(50,), dtype=float32) 
 (50,)


### One-hot encoding tensors

In [110]:
# Create a list of indicies
some_list = [0, 1, 2, 3] # Could be red, green, blue, purple

#One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squaring, log, square root

In [111]:
# Create a new tensor

H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [112]:
# Square it

tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [116]:
# Find the squareroot

tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [120]:
# Find the log

tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifuly with NumPy

In [122]:
# Create a tensor directly form a NumPy array

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [123]:
# Convert our tensor back to a NumPy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [124]:
# Convert tensor J to a NumPy array

J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [128]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [132]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding acces to GPUs

In [134]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [137]:
tf.config.list_physical_devices("GPU")

[]

In [136]:
!nvidia-smi

Mon Jan 23 15:55:41 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.78.01    Driver Version: 525.78.01    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8    N/A /  N/A |      7MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automaticly use it if possible